name: gace_camo
description: A Flutter app for camouflage detection using TFLite
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ML / image handling
  image: ^4.0.21
  tflite_flutter: ^0.12.1

  # Permissions & file access
  permission_handler: ^10.4.0
  file_picker: ^5.2.3
  path_provider: ^2.0.11
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite

